# Generated by Django 3.0.8 on 2021-01-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210113_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
        migrations.DeleteModel(
            name='BuingList',
        ),
    ]
