# Generated by Django 3.0.8 on 2021-01-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210114_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
