# Generated by Django 3.0.8 on 2021-01-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shoplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoplist',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
